var indexconfig =
    [
        {
            "IndexName": "文化部典藏網",
            "IndexCode": "MOCCOLLECTIONS",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "時間資訊": "Date",
                "最後更新時間": "LastUpdateTime",
                "作者": "Creator",
                "資源類型": "Keyword_Type",
                "數位物件類型": "Keyword_Format",
                "語言": "Keyword_Language",
                "向量空間資料": "Geometry",
                "空間資訊": "PlaceName",
                "空間資料類型": "Keyword_Spatial",
                "典藏機關": "Owner"
            }
        },
        {
            "IndexName": "國家文化資料庫",
            "IndexCode": "online_metadata",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "別名": "alternativeTitle",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "keywords",
                "創作者": "Creator",
                "出版者": "publisher",
                "其他貢獻者": "contributor",
                "格式": "format",
                "創作日期": "date",
                "資料來源": "source",
                "作品語文": "language",
                "全集/系列名": "relation",
                "相關人名": "people",
                "相關地點": "coverageSpatial",
                "數位物件類型": "Keyword_Format",
                "內容主題": "type"
            }
        },
        {
            "IndexName": "收存系統-活動事件",
            "IndexCode": "Culture_Event",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "關鍵字": "Keywords",
                "時間起": "startDate",
                "時間迄": "endDate",
                "最後更新時間": "LastUpdateTime",
                "時間分期": "timelines",
                "地點-名稱": "place",
                "地點-縣市區": "city",
                "地點-地址": "address",
                "地點-經度": "lng",
                "地點-緯度": "lat",
                "參考資料": "sameAs",
                "活動主辦單位": "organizer",
                "貢獻者": "contributors",
                "撰寫者": "contributor",
                "活動網址": "eventUrl",
                "演出者/主要人物": "performers",
                "時間長度": "lengthOfTime",
                "建檔單位": "createOrgName",
                "資料來源": "dataSource",
                "相關作品": "workFeatured"
            }
        },
        {
            "IndexName": "收存系統-影音",
            "IndexCode": "Culture_Media",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "副標題": "alternativeHeadline",
                "關鍵字": "Keywords",
                "時間資訊": "dates",
                "最後更新時間": "LastUpdateTime",
                "創作者": "Creator",
                "出版者": "publisher",
                "媒體類型": "mediaType",
                "資料使用語言": "language",
                "時間分期": "timelines",
                "地點-縣市區": "city",
                "地點-地址": "address",
                "地點-經度": "lng",
                "地點-緯度": "lat",
                "參考資料": "sameAs",
                "貢獻者": "contributors",
                "撰寫者": "contributor",
                "尺寸": "size",
                "管理者": "admin",
                "材質": "material",
                "得獎紀錄": "award",
                "創作中的虛構角色": "character",
                "創作內容指涉地點": "contentLocation",
                "取得方式": "acquireWay",
                "取得對象": "acquireSource",
                "存放位置": "storage",
                "版本": "version",
                "ISBN": "isbn",
                "線上授權連結": "onlineAuthLink",
                "建檔單位": "createOrgName",
                "資料來源": "citation"
            }
        },
        {
            "IndexName": "收存系統-人物",
            "IndexCode": "Culture_People",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "關鍵字": "Keywords",
                "出生年月日": "bornStr",
                "卒年月日": "deathStr",
                "最後更新時間": "LastUpdateTime",
                "撰寫者": "Creator",
                "資料使用語言": "language",
                "資料來源": "dataSource",
                "時間分期": "timelines",
                "出生地點-名稱": "bornPlace",
                "出生地點-地址": "bornAddress",
                "出生地點-縣市區": "bornCity",
                "卒年地點-名稱": "deathPlace",
                "卒年地點-地址": "deathAddress",
                "卒年地點-縣市區": "deathCity",
                "參考資料": "sameAs",
                "線上授權連結": "onlineAuthLink",
                "職稱": "job",
                "參與組織": "organization",
                "專長": "expertise",
                "工作單位": "worksFor",
                "性別": "gender",
                "國籍": "citizenship",
                "出生地點-經度": "bornLng",
                "出生地點-緯度": "bornLat",
                "卒年地點-經度": "deathLng",
                "卒年地點-緯度": "deathLat",
                "建檔單位": "createOrgName",
                "網站、FB": "url"
            }
        },
        {
            "IndexName": "收存系統-組織",
            "IndexCode": "Culture_Organization",
            "IgnoreDate": ['foundingDate', 'dissolutionDate'],
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alternateName",
                "關鍵字": "Keywords",
                "創辦日期": "foundingDate",
                "解散日期": "dissolutionDate",
                "最後更新時間": "LastUpdateTime",
                "撰寫者": "Creator",
                "時間分期": "timelines",
                "創辦地-名稱": "foundingLoactionName",
                "創辦地-地址": "foundingLocationAddress",
                "登記地-地址": "registerLocationAddress",
                "聯絡地-地址": "contactLocationAddress",
                "參考資料": "sameAs",
                "創辦地-經度": "foundingLocationLongitude",
                "創辦地-緯度": "foundingLocationLatitude",
                "登記地-經度": "registerLocationLongitude",
                "登記地-緯度": "registerLocationLatitude",
                "聯絡地-經度": "contactLocationLongitude",
                "聯絡地-緯度": "contactLocationLatitude",
                "統一編號": "taxId",
                "創辦人": "founder",
                "傑出成員": "alumni",
                "連絡電話": "contactPhone",
                "連絡email": "contactEmail",
                "建檔單位": "createOrgName",
                "資料來源": "dataSource"
            }
        },
        {
            "IndexName": "收存系統-空間",
            "IndexCode": "Culture_Place",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "關鍵字": "Keywords",
                "史料時間": "historicalDates",
                "最後更新時間": "LastUpdateTime",
                "時間分期": "timelines",
                "所在地-名稱": "place",
                "所在地-地址": "address",
                "所在地-經度": "longitude",
                "所在地-緯度": "latitude",
                "電話": "phone",
                "事件": "Event",
                "相關人物": "relationPeople",
                "是否開放": "open",
                "免費進場": "free",
                "開放時間": "openTime",
                "開放時間說明": "openTimeDescription",
                "可容納人數": "capacity",
                "交通方式": "traffic",
                "隸屬": "subjection",
                "地圖圖標": "tag",
                "現況": "situation",
                "史料摘要": "historicalDataBrief",
                "史料原文/譯文": "historicalData",
                "參考資料": "reference",
                "撰寫者": "writer",
                "建檔單位": "createOrgName",
                "資料來源": "source"
            }
        },
        {
            "IndexName": "收存系統-作品文物",
            "IndexCode": "Culture_Object",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "副標題": "alternativeHeadline",
                "關鍵字": "Keywords",
                "時間資訊": "dates",
                "最後更新時間": "LastUpdateTime",
                "創作者": "Creator",
                "出版者": "publisher",
                "媒體類型": "mediaType",
                "資料使用語言": "language",
                "時間分期": "timelines",
                "地點-縣市區": "city",
                "地點-地址": "address",
                "地點-經度": "lng",
                "地點-緯度": "lat",
                "貢獻者": "contributors",
                "撰寫者": "contributor",
                "尺寸": "size",
                "管理者": "admin",
                "得獎紀錄": "award",
                "創作中的虛構角色": "character",
                "創作內容指涉地點": "contentLocation",
                "取得方式": "acquireWay",
                "取得對象": "acquireSource",
                "存放位置": "storage",
                "版本": "version",
                "ISBN": "isbn",
                "線上授權連結": "onlineAuthLink",
                "材質": "stuff",
                "參考資料": "url",
                "建檔單位": "createOrgName",
                "資料來源": "citation"
            }
        },
        {
            "IndexName": "收存系統-踏查路線",
            "IndexCode": "Culture_Route",
            "IgnoreDate": ['dateStart', 'dateEnd'],
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "史料日期起": "dateStart",
                "史料日期迄": "dateEnd",
                "最後更新時間": "LastUpdateTime",
                "時間分期": "timelines",
                "踏查地點": "map_points",
                "撰寫者": "contributor",
                "史料原文/譯文": "historicalData",
                "參考資料": "reference",
                "建檔單位": "createOrgName",
                "資料來源": "source"
            }
        },
        {
            "IndexName": "收存系統-無形文化資產",
            "IndexCode": "Culture_Invisible",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "別名": "alias",
                "關鍵字": "Keywords",
                "舉行時間": "time",
                "辦理週期": "week",
                "儀式過程及重要特徵": "ceremonyFeature",
                "地點-縣市區": "city",
                "歷史源流發展概況": "historyDevelopment",
                "傳統地理區域描述": "landDescription",
                "所屬族群": "group",
                "所屬族群說明": "groupText",
                "技藝/流派": "skillSect",
                "主辦單位": "organization",
                "撰寫者": "contributor",
                "保存者/保存團體": "preserver",
                "建檔單位": "createOrgName",
                "資料來源": "dataSource"
            }
        },
        {
            "IndexName": "臺灣故事島",
            "IndexCode": "Comm_New_Story",
            "IgnoreDate": ['StorySDate', 'FirstPassDate'],
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "時間資訊": "StorySDate",
                "作者": "Creator",
                "空間資訊": "InterviewLocation",
                "受訪者": "Respondents",
                "首播日期": "FirstPassDate",
                "故事檔名": "MovieName"
            }
        },
        {
            "IndexName": "公共藝術網",
            "IndexCode": "v_efa",
            "DetailColumns": {
                "描述": ["Description", "plan_desc", "description_en"],
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "作者": "Creator",
                "創作年代": "admin_creation_createdyear",
                "尺寸": "size",
                "材質": "material",
                "地點": "location",
                "經費": "outlay",
                "委託單位": "agency",
                "執行小組": "executive",
                "徵選小組": "committee"
            }
        },
        {
            "IndexName": "國立臺灣大學",
            "IndexCode": "NTU",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "時間資訊": "Date",
                "作者": "Creator",
                "出版者": "Publisher",
                "貢獻者/其他參與者": "Contributor",
                "簡述的創建者": "DescriptionCreator",
                "資源類型": "Type",
                "數位物件類型": "Format",
                "語言": "Language"
            }
        },
        {
            "IndexName": "國史館",
            "IndexCode": "drnh",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "全宗號": "zong",
                "全宗名稱": "Creator",
                "卷件開始日期": "Date",
                "卷件結束日期": "to_date",
                "數位物件類型": "Format",
                "全宗系列": "series",
                "相關人員": "person",
                "相關地點": "PlaceName",
                "關鍵詞組": "Keywords"
            }
        },
        {
            "IndexName": "臺灣文獻館文獻檔案",
            "IndexCode": "th",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵詞": "Keywords",
                "時間資訊": "startDate",
                "最後更新時間": "LastUpdateTime",
                "出版者": "orgInfo",
                "數位物件類型": "DoType",
                "空間資訊": "topoInfo"
            }
        },
        {
            "IndexName": "臺中學",
            "IndexCode": "TSNCDM",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "時間資訊": "Date",
                "作者": "Creator",
                "出版者": "Publisher",
                "類型": "Keyword_Type",
                "數位物件類型": "Keyword_Format",
                "語言": "Keyword_Language",
                "臺中的時期": "CoverageTemporal",
                "地點": "PlaceName",
                "提供者": "Provider",
                "關聯資源": "RelatedResources"
            }
        },
        {
            "IndexName": "國立故宮博物院-書畫",
            "IndexCode": "NPM_Painting",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "藏品類型": "CollectionType",
                "作者": "Creator",
                "書體": "Script",
                "色彩": "Color",
                "裝裱形式": "AppearDescription",
                "創作時間": "CreatedTime",
                "數量": "Quantity",
                "作品語文": "Language",
                "集叢號-件": "SeriesJian",
                "集叢號-開": "SeriesKai",
                "集叢號-幅": "SeriesFu",
                "集叢號-類型": "Type",
                "典藏尺寸": "Dimension",
                "質地": "Material",
                "題跋資料": "TIBA",
                "印記資料": "SEAL",
                "主題": "Subject",
                "技法": "Technique",
                "品名": "Title",
                "參考資料": "Reference"
            }
        },
        {
            "IndexName": "國立故宮博物院-器物",
            "IndexCode": "NPM_Utensils",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "品名-英文": "EnglishTitle",
                "類別": "CollectionType",
                "質材": "Type",
                "功能": "Functions",
                "尺寸": "Dimension",
                "時代": ["ChineseDisplay", "WestDisplay"], 
                "款識": "Inscription",
                "參考資料": "Publication"
            }
        },
        {
            "IndexName": "國家文化資產網-古蹟資料",
            "IndexCode": "BOCH_CountryCulture_11",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "現況地址_地址": "address",
                "現況地址_縣市": "cityName",
                "現況地址_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "現狀": "buildingActualState",
                "外觀特徵": "buildingFeatures",
                "應重點維護之事項": "buildingKeyMaintainItem",
                "主管機關聯絡地址": "govDeptAddress",
                "主管機關單位": "govDeptName",
                "主管機關聯絡電話": "govDeptPhone",
                "主管機關名稱": "govInstitution",
                "所屬主管機關": "govInstitutionName",
                "室內特徵": "inHouseFeatures",
                "評定基準": "judgeCriteria",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "指定（登錄）理由": "registerReason",
                "網址": "wenSiteaddress",
                "網站名稱": "wenSitename"
            }
        },
        {
            "IndexName": "國家文化資產網-歷史建築資料",
            "IndexCode": "BOCH_CountryCulture_12",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "現狀": "buildingActualState",
                "外觀特徵": "buildingFeatures",
                "應重點維護之事項": "buildingKeyMaintainItem",
                "使用情形": "buildingUsage",
                "主管機關聯絡地址": "govDeptAddress",
                "主管機關單位": "govDeptName",
                "主管機關聯絡電話": "govDeptPhone",
                "主管機關名稱": "govInstitution",
                "所屬主管機關": "govInstitutionName",
                "室內特徵": "inHouseFeatures",
                "是否收費": "isCharge",
                "是否開放": "isOpenVisit",
                "評定基準": "judgeCriteria",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "開放時間": "openUpTime",
                "歷史沿革資料來源": "pastHistorySource",
                "指定（登錄）理由": "registerReason",
                "網址": "wenSiteaddress",
                "網站名稱": "wenSitename"
            }
        },
        {
            "IndexName": "國家文化資產網-聚落建築群資料",
            "IndexCode": "BOCH_CountryCulture_13",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "建築形式與景觀特色": "architecturehFeature",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "應重點維護之事項": "buildingKeyMaintainItem",
                "建號": "buildingSerialNo",
                "使用情形": "buildingUsage",
                "地區發展與特色": "communityDevelop",
                "所屬主管機關": "govInstitutionName",
                "歷史脈絡與保存價值": "historyValue",
                "評定基準": "judgeCriteria",
                "區域範圍劃定": "landScope",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "備註": "notes",
                "指定（登錄）理由": "registerReason"
            }
        },
        {
            "IndexName": "國家文化資產網-紀念建築資料",
            "IndexCode": "BOCH_CountryCulture_14",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "現狀": "buildingActualState",
                "外觀特徵": "buildingFeatures",
                "應重點維護之事項": "buildingKeyMaintainItem",
                "使用情形": "buildingUsage",
                "主管機關聯絡地址": "govDeptAddress",
                "主管機關單位": "govDeptName",
                "主管機關聯絡電話": "govDeptPhone",
                "主管機關名稱": "govInstitution",
                "所屬主管機關": "govInstitutionName",
                "室內特徵": "inHouseFeatures",
                "是否收費": "isCharge",
                "是否開放": "isOpenVisit",
                "評定基準": "judgeCriteria",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "開放時間": "openUpTime",
                "歷史沿革資料來源": "pastHistorySource",
                "指定（登錄）理由": "registerReason",
                "網址": "wenSiteaddress",
                "網站名稱": "wenSitename"
            }
        },
        {
            "IndexName": "國家文化資產網-考古遺址資料",
            "IndexCode": "BOCH_CountryCulture_21",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
              "現狀": "actualStatus",
              "所在地理區域_地址": "address",
              "所在地理區域_縣市": "cityName",
              "所在地理區域_區": "distName",
              "公告類別": "classification",
              "公告備註": "note",
              "公告文號": "officialDocNo",
              "公告日期": "registerDate",
              "級別名稱": "assetsClassifyName",
              "文化意義": "cultralMean",
              "發現原因說明": "discoveryDescription",
              "所屬主管機關": "govInstitutionName",
              "評定基準": "judgeCriteria",
              "定著土地之範圍": "landScope",
              "土地使用狀況": "landUsage",
              "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
              "都市地區使用種類": "cityLandUseType",
              "都市地區使用種類其他說明": "cityLandUseTypeOther",
              "定著土地範圍(公告地號)_縣市": "LandlotcityName",
              "定著土地範圍(公告地號)_區": "LandlotdistName",
              "定著土地範圍(公告地號)_項次": "LandlotitemNo",
              "定著土地範圍(公告地號)_大小段": "landNo",
              "定著土地範圍(公告地號)_地號": "landSerialNo",
              "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
              "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
              "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
              "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
              "緯度": "latitude",
              "法令依據": "lawsReference",
              "經度": "longitude",
              "影音多媒體圖片_檔案網址": "MediaImageurl",
              "影音多媒體影片_檔案網址": "MediaVideourl",
              "鄰近遺址核對說明": "nearbyArcheologyBrief",
              "鄰近遺址核對": "nearbyArcheologyCheck",
              "鄰近地標": "neighborPosition",
              "指定（登錄）理由": "registerReason",
              "相對位置": "relativePosition",
              "使用情形": "usageStatus"
            }
        },
        {
            "IndexName": "國家文化資產網-文化景觀資料",
            "IndexCode": "BOCH_CountryCulture_31",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "現況": "actualState",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "內容與範圍": "content",
                "特徵": "feature",
                "所屬主管機關": "govInstitutionName",
                "評定基準": "judgeCriteria",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "關連之具有歷史、文化、藝術、科學價值之口傳、文獻資料或生活、儀式行為": "landscapeRelated",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "備註": "notes",
                "指定（登錄）理由": "registerReason",
                "特殊價值": "specialValue"
            }
        },
        {
            "IndexName": "國家文化資產網-史蹟資料",
            "IndexCode": "BOCH_CountryCulture_32",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "現況": "actualState",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "內容與範圍": "content",
                "特徵": "feature",
                "所屬主管機關": "govInstitutionName",
                "評定基準": "judgeCriteria",
                "土地使用狀況": "landUsage",
                "定著土地範圍(公告地號)_都市使用流水號 1. 都市區 2. 非都市區": "cityLandUse",
                "都市地區使用種類": "cityLandUseType",
                "都市地區使用種類其他說明": "cityLandUseTypeOther",
                "定著土地範圍(公告地號)_縣市": "LandlotcityName",
                "定著土地範圍(公告地號)_區": "LandlotdistName",
                "定著土地範圍(公告地號)_項次": "LandlotitemNo",
                "定著土地範圍(公告地號)_大小段": "landNo",
                "定著土地範圍(公告地號)_地號": "landSerialNo",
                "定著土地範圍(公告地號)_所有權屬流水號 1. 公有 2. 私有 3. 公私有": "landownership",
                "定著土地範圍(公告地號)_非都市地區使用子種類": "noncityLandUseSubType",
                "定著土地範圍(公告地號)_非都市地區使用種類": "noncityLandUseType",
                "定著土地範圍(公告地號)_非都市地區使用種類其他說明": "noncityLandUseTypeOther",
                "關連之具有歷史、文化、藝術、科學價值之口傳、文獻資料或生活、儀式行為": "landscapeRelated",
                "緯度": "latitude",
                "法令依據": "lawsReference",
                "經度": "longitude",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "備註": "notes",
                "指定（登錄）理由": "registerReason",
                "特殊價值": "specialValue"
            }
        },
        {
            "IndexName": "國家文化資產網-傳統表演藝術資料",
            "IndexCode": "BOCH_CountryCulture_41",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "所屬族群_族群名稱": "computeTypeName",
                "所屬族群_其他備註": "computeTypeOtherRemark",
                "所屬族群_類別名稱": "computeTypeType",
                "所屬主管機關": "govInstitutionName",
                "評定基準": "judgeCriteria",
                "法令依據": "lawsReference",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "保存者/保存團體": "recorder",
                "指定（登錄）理由": "registerReason"
            }
        },
        {
            "IndexName": "國家文化資產網-傳統工藝資料",
            "IndexCode": "BOCH_CountryCulture_42",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "現況地址_地址": "address",
                "現況地址_縣市": "cityName",
                "現況地址_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "所屬族群_族群名稱": "computeTypeName",
                "所屬族群_其他備註": "computeTypeOtherRemark",
                "所屬族群_類別名稱": "computeTypeType",
                "所屬主管機關": "govInstitutionName",
                "評定基準": "judgeCriteria",
                "法令依據": "lawsReference",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "保存者/保存團體": "recorder",
                "指定（登錄）理由": "registerReason"
            }
        },
        {
            "IndexName": "國家文化資產網-民俗資料",
            "IndexCode": "BOCH_CountryCulture_51",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "民俗活動_儀式資料": "ActivitiesCeremonies",
                "民俗活動_簡介": "ActivitiesDescription",
                "民俗活動_舉行時間-迄": "ActivitiesHoldEnd",
                "民俗活動_舉行時間-起": "ActivitiesHoldStart",
                "民俗活動_農曆舉行時間-迄": "ActivitieslunarHoldEnd",
                "民俗活動_農曆舉行時間-起": "ActivitiesLunarHoldStart",
                "民俗活動_活動名稱": "ActivitiesName",
                "民俗活動_備註": "ActivitiesNote",
                "民俗活動_相關網站": "ActivitiesWebsite",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "儀式祭典_行事說明": "CeremoniesDescription",
                "儀式祭典_舉行日期方式": "CeremoniesHoldDay",
                "儀式祭典_圖像": "CeremoniesImages",
                "儀式祭典_影片": "CeremoniesMedias",
                "儀式祭典_名稱": "CeremoniesName",
                "儀式祭典_時程": "CeremoniesSchedule",
                "儀式過程及重要特徵": "ceremonyFeature",
                "所屬族群_族群名稱": "computeTypeName",
                "所屬族群_其他備註": "computeTypeOtherRemark",
                "所屬族群_類別名稱": "computeTypeType",
                "特色_特色說明": "FeaturesDescription",
                "特色_圖像": "FeaturesImages",
                "特色_標題": "FeaturesName",
                "所屬主管機關": "govInstitutionName",
                "舉行時間類別(國曆/農曆)": "holdCalendarType",
                "辦理週期": "holdPeriod",
                "舉行時間日": "holdStartDay",
                "舉行時間月": "holdStartMonth",
                "主辦單位-地址": "hostContactorAddress",
                "主辦單位-聯絡電話": "hostContactorPhone",
                "主辦單位-名稱": "hostUnitName",
                "評定基準": "judgeCriteria",
                "法令依據": "lawsReference",
                "陣頭_介紹": "LopsDescription",
                "陣頭_圖像": "LopsImages",
                "陣頭_影像": "LopsMedias",
                "陣頭_陣名": "LopsName",
                "陣頭_備註": "LopsRemark",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "保存者/保存團體": "recorder",
                "指定（登錄）理由": "registerReason",
                "禁忌": "taboos"
            }
        },
        {
            "IndexName": "國家文化資產網-口述傳統",
            "IndexCode": "BOCH_CountryCulture_52",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "儀式過程及重要特徵": "ceremonyFeature",
                "所屬族群_族群名稱": "computeTypeName",
                "所屬族群_其他備註": "computeTypeOtherRemark",
                "所屬族群_類別名稱": "computeTypeType",
                "所屬主管機關": "govInstitutionName",
                "主辦單位-地址": "hostContactorAddress",
                "主辦單位-聯絡電話": "hostContactorPhone",
                "主辦單位-名稱": "hostUnitName",
                "評定基準": "judgeCriteria",
                "法令依據": "lawsReference",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "發生時間與地點_圖像": "occurrencesImages",
                "發生時間與地點_地點說明": "occurrenceslocation",
                "發生時間與地點_影片": "occurrencesMedias",
                "發生時間與地點_標題": "occurrencesName",
                "發生時間與地點_時間說明": "occurrencesTimeDescription",
                "保存者/保存團體": "recorder",
                "指定（登錄）理由": "registerReason"
            }
        },
        {
            "IndexName": "國家文化資產網-傳統知識與實踐資料",
            "IndexCode": "BOCH_CountryCulture_53",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "儀式過程及重要特徵": "ceremonyFeature",
                "所屬族群_族群名稱": "computeTypeName",
                "所屬族群_其他備註": "computeTypeOtherRemark",
                "所屬族群_類別名稱": "computeTypeType",
                "所屬主管機關": "govInstitutionName",
                "舉行時間類別(國曆/農曆)": "holdCalendarType",
                "辦理週期": "holdPeriod",
                "舉行時間日": "holdStartDay",
                "舉行時間月": "holdStartMonth",
                "主辦單位-地址": "hostContactorAddress",
                "主辦單位-聯絡電話": "hostContactorPhone",
                "主辦單位-名稱": "hostUnitName",
                "評定基準": "judgeCriteria",
                "法令依據": "lawsReference",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "發生時間與地點_圖像": "occurrencesImages",
                "發生時間與地點_地點說明": "occurrenceslocation",
                "發生時間與地點_影片": "occurrencesMedias",
                "發生時間與地點_標題": "occurrencesName",
                "發生時間與地點_時間說明": "occurrencesTimeDescription",
                "保存者/保存團體": "recorder",
                "指定（登錄）理由": "registerReason"
            }
        },
        {
            "IndexName": "國家文化資產網-古物資料",
            "IndexCode": "BOCH_CountryCulture_61",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "所在地理區域_地址": "address",
                "所在地理區域_縣市": "cityName",
                "所在地理區域_區": "distName",
                "數量": "amount",
                "公告類別": "classification",
                "公告備註": "note",
                "公告文號": "officialDocNo",
                "公告日期": "registerDate",
                "級別名稱": "assetsClassifyName",
                "種類名稱": "name",
                "其他說明": "other",
                "總類子類別名稱": "subName",
                "年代": "descAge",
                "作者": "descCreator",
                "材質": "descMaterial",
                "尺寸": "descSize",
                "保存環境": "environment",
                "所屬主管機關": "govInstitutionName",
                "評定基準": "judgeCriteria",
                "所有人或保管人姓名": "keepDeptsCustodian",
                "保管單位名稱": "keepDeptsName",
                "所在地地址": "keepPlacesAddress",
                "所在地名稱": "KeepPlacesName",
                "保存空間屬性": "KeepPlacesSaveSpace",
                "保存空間文資身分": "KeepPlacesSaveSpaceIdentity",
                "法令依據": "lawsReference",
                "管理維護": "manageMaintain",
                "影音多媒體圖片_檔案網址": "MediaImageurl",
                "影音多媒體影片_檔案網址": "MediaVideourl",
                "備註": "notes",
                "古物出處/出處或來源": "pastHistorySource",
                "出處或來源說明": "pastHistorySourceNotes",
                "指定（登錄）理由": "registerReason",
                "典藏或財產編號": "reservationCode",
                "保存現狀": "reserveStatus"
            }
        },
        {
            "IndexName": "國家檔案資訊網",
            "IndexCode": "Archives",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "主題": "Keywords",
                "檔案起迄日期": "DateValue",
                "全宗名": "Creator",
                "數位物件類型": "Keyword_Format",
                "媒體型式": "Keyword_Type",
                "地點資訊": "Placename",
                "檔案典藏機關": "DescriptionCreator"
            }
        },
        {
            "IndexName": "李梅樹紀念館",
            "IndexCode": "Limeishu",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "高": "height",
                "寬": "width",
                "語言": "language",
                "來源": "source",
                "創作者": "Creator",
                "貢獻者": "contributor",
                "發行者": "publisher",
                "年代範圍": "coverage",
                "創作日期": "date",
                "檔案大小": "filesize",
                "每英寸點數": "DPI",
                "類別與關鍵字": "type"
            }
        },
        {
            "IndexName": "文訊雜誌社",
            "IndexCode": "WenHsun",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "圖片庫關鍵字": "Keywords",
                "人物資訊": "people_info",
                "事件名稱": "event_name",
                "拍攝時間": "filming_date",
                "拍攝地點": "filming_location",
                "入藏來源": "photo_source"
            }
        },
        {
            "IndexName": "中國文化大學",
            "IndexCode": "PCCU",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "關鍵字": "Keywords",
                "時間資訊": "Date",
                "空間資訊": "Location",
                "數位物件類型": "Format",
                "資源類型": "ResourceType",
                "語言": "Language",
                "作者": "Creator",
                "出版者": "Publisher",
                "數量": "Count",
                "單位": "Unit",
                "尺寸": "Size",
                "關聯人物": "RelatedPeople",
                "補充資料": "Additional",
                "課程名稱": "ClassName",
                "全集系列": "SeriesName",
                "簡述的創建者": "Owner"
            }
        },
        {
            "IndexName": "財團法人吳三連台灣史料基金會",
            "IndexCode": "Thmcenter",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "數位物件類型": "Keyword_Format",
                "最後更新時間": "LastUpdateTime",
                "關鍵字": "Keywords",
                "時間資訊": "time",
                "相關人物": "people",
                "資源類型": "resource_type",
                "語言": "language",
                "作者": "Creator",
                "簡述的創建者": "metadata_author",
                "介接機關/系統": "_from",
                "審核者": "reviewer",
                "資料異動註記": "status",
                "歷史分期": "period",
                "參考文獻": "reference"
            }
        },
        {
            "IndexName": "財團法人陳澄波文化基金會",
            "IndexCode": "Taifuten_object",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "資料分類": "data_type",
                "名稱原文": "object_title",
                "創作者": "Creator",
                "時間資訊": "object_data",
                "地點資訊": "object_location_address",
                "展覽名稱": "object_exhibition",
                "屆數": "object_exhibition_session",
                "畫部": "object_exhibition_type",
                "資格": "object_exhibition_qualifications",
                "獎項": "object_reward",
                "關鍵字": "Keywords",
                "參考資料": "object_references",
                "撰寫者": "object_description_author",
                "更新時間": "LastUpdateTime",
                "資料異動註記": "update_note"
            }
        },
        {
            "IndexName": "財團法人陳澄波文化基金會",
            "IndexCode": "Taifuten_artist",
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "Original_Url",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "資料分類": "data_type",
                "讀音": "artist_pronunciation",
                "別名": "artist_alternatename",
                "性別": "artist_gender",
                "出生地": "artist_birth_address",
                "出生年月日": "artist_birthday",
                "卒年月日": "artist_end",
                "臺府展入選屆別（年）": "artist_taifu_number",
                "資格": "artist_taifu_award",
                "父母": "artist_parent",
                "兄弟姊妹": "artist_sibling",
                "配偶": "artist_spouse",
                "關鍵字": "Keywords",
                "參考資料": "object_references",
                "撰寫者": "Creator",
                "更新時間": "LastUpdateTime",
                "資料異動註記": "update_note"
            }
        },
        {
            "IndexName": "創作區素材",
            "IndexCode": "member_material",
            "IgnoreDate": ['date_modify'],
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "年份": ["year_mode", "year"],
                "最後更新時間": "date_modify",
                "作者": "Creator",
                "經度": "Keyword_Longitude",
                "緯度": "Keyword_Latitude",
                "空間資訊": ["city", "area", "location"],
                "時間資訊": ["date_material", "date_material_str"],
                "關鍵字": ["keyword"]
            }
        },
        {
            "IndexName": "創作區故事",
            "IndexCode": "member_story",
            "IgnoreDate": ['date_modify'],
            "DetailColumns": {
                "描述": "Description",
                "數位物件授權狀態": "Keyword_Rights_2",
                "描述授權狀態": "Keyword_Des_Rights_2",
                "位置資訊經度": "Keyword_Longitude",
                "位置資訊緯度": "Keyword_Latitude",
                "原始資料連結": "",
                "來源識別號": "Original_Identifier",
                "主題分類": "Keyword_Subject_1",
                "年份": ["year_mode", "year"],
                "最後更新時間": "date_modify",
                "作者": "Creator",
                "經度": "Keyword_Longitude",
                "緯度": "Keyword_Latitude",
                "空間資訊": ["city", "area", "location"]
            }
        }
    ]
    ;